### ISSUE TITLE
Pre tags sometimes disappear 

### ISSUE THREAD

**Issue by kezz** [KyoriPowered/adventure-text-minimessage#135]
See the difference between [this](https://webui.adventure.kyori.net/?mode=chat_closed&input=Hello%20%3Cpre%3Etest%3C%2Fpre%3E%3C%2Fpre%3E%20yoo) and [that](https://webui.adventure.kyori.net/?mode=chat_closed&input=Hello%20%3Cpre%3Etest%3C%2Fpre%3Etest%3C%2Fpre%3E%20yoo).

**Comment by MiniDigger** [comment]
I bet this is fixed by #132

**Comment by rymiel** [comment]
This can be closed? I guess the *bad* thing about using the webui for repro is not being able to see what it was before because it looks fine now?

**Comment by kezz** [comment]
It still doesn't work sadly. With input `Hello <pre>test</pre></pre> yoo` you should expect to "see" `Hello test</pre> yoo` for example.

**Comment by rymiel** [comment]
Oh, I guess i misread the input, even just https://webui.adventure.kyori.net/?mode=chat_closed&input=Hello%20%3C%2Fpre%3E%20yoo is broken so apparently closing pre tags just never show up

**Comment by kezz** [comment]
> no closing tags ever show up... Is this expected behaviour?

Did they show up on 4.1.0-SNAPSHOT?

**Comment by rymiel** [comment]
> Did they show up on 4.1.0-SNAPSHOT?

I don't have a great example to show but a plugin still using 4.1.0-SNAPSHOT seems to preserve them
![image](https://user-images.githubusercontent.com/53803019/128763964-6ea62bcb-0d28-41c5-ba94-fe2afcb307b9.png)
![image](https://user-images.githubusercontent.com/53803019/128763944-41264d92-f28b-4b17-b0d2-9a8d5655ec29.png)

**Comment by zml2008** [comment]
No longer relevant due to #149
